spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://labs-test.postgres.database.azure.com:5432/labs
    username: postgres@labs-test
    password: unalTest2018
    continueOnError: true

  jpa:
    database: POSTGRESQL
    show-sql: false
server:
  port: 8082
